const app = require('../src/main');
const http = require('http');
const axios = require('axios');

const PORT = 3008;
const BASE_URL = `http://localhost:${PORT}/api/v1`;

async function runTests() {
    console.log('--- Testing Remaining Modules (Shop, Performance, Reports) ---');

    // Start Server
    const server = http.createServer(app);
    await new Promise(resolve => server.listen(PORT, resolve));
    console.log(`Test Server running on port ${PORT}`);

    try {
        // Test 1: Officer Performance
        console.log('[TEST 1] Fetching Officer Performance Leaderboard...');
        const perfRes = await axios.get(`${BASE_URL}/admin/officer-performance`);
        if (perfRes.data.success && Array.isArray(perfRes.data.data)) {
            console.log(`✅ PASS: Performance data fetched. Count: ${perfRes.data.data.length}`);
            if (perfRes.data.data.length > 0) {
                console.log(`   - Top Officer: ${perfRes.data.data[0].name} (Score: ${perfRes.data.data[0].score})`);
            }
        } else {
            console.error('❌ FAIL: Invalid performance response', perfRes.data);
        }

        // Test 2: CAG Audit Report
        console.log('[TEST 2] Fetching CAG Audit Report...');
        const reportRes = await axios.get(`${BASE_URL}/reports/cag-audit`);
        if (reportRes.data.success && reportRes.data.data) {
            console.log(`✅ PASS: Audit Report fetched.`);
            console.log(`   - Generated By: ${reportRes.data.data.generatedBy}`);
            console.log(`   - Current Stock: ${reportRes.data.data.stats.currentStock}`);
        } else {
            console.error('❌ FAIL: Invalid audit report response', reportRes.data);
        }

        // Test 3: Shop Acceptance (Trip Scan)
        // First create a trip to scan
        console.log('[TEST 3] Testing Shop Acceptance (Trip Scan)...');
        const tripRes = await axios.post(`${BASE_URL}/trips`, {
            truckId: "TN-SCAN-TEST",
            origin: "Origin",
            destination: "Dest",
            driverId: "D1"
        });
        const tripId = tripRes.data.data.id;

        // Scan it with valid weight
        const scanRes = await axios.post(`${BASE_URL}/trips/${tripId}/scan`, {
            scannedTripId: tripId,
            receivedWeight: 10000, // Assuming default load is 10000
            shopId: "SHOP-001"
        });

        if (scanRes.data.success) {
            console.log(`✅ PASS: Shop Acceptance Scan successful.`);
        } else {
            console.error('❌ FAIL: Shop Scan failed', scanRes.data);
        }

        // Scan with Discrepancy (Theft)
        const theftRes = await axios.post(`${BASE_URL}/trips/${tripId}/scan`, {
            scannedTripId: tripId,
            receivedWeight: 8000, // 2000kg less
            shopId: "SHOP-001"
        });

        if (theftRes.data.success && theftRes.data.alert) {
            console.log(`✅ PASS: Theft Alert generated correctly for weight discrepancy.`);
            console.log(`   - Alert: ${theftRes.data.alert.message}`);
        } else {
            console.error('❌ FAIL: Theft detection failed', theftRes.data);
        }


    } catch (error) {
        console.error('❌ FAIL: Request failed', error.message);
        if (error.response) console.error('   Response:', error.response.data);
    } finally {
        server.close();
        console.log('Test Server Stopped.');
    }
}

runTests();
